### ISSUE TITLE
F001 - Instanciar projeto React para o frontend

### ISSUE THREAD

**Issue by Mateus-Gabardo** [Mateus-Gabardo/Droneseta-E-commerce-frontend#1]
Instanciar projeto React  com o nome Dronesete-frontend e subir o projeto no gitHub

**Comment by GustavoRosaLemos** [comment]
Foi criado o projeto de React seguindo conceitos fundamentados no mercado profissional de software.

Para executar, deve-se utilizar o gerenciador de pacote _Yarn_.

https://github.com/GustavoRosaLemos/droneseta-e-commerce-frontend
